### ISSUE TITLE
unable to build using npm

### ISSUE THREAD

**Issue by Retamogordo** [nanofuxion/arjs-react#1]
Hi,
I have just came across this repo which looks quite promising for my little project in React,
however I failed to build it due to a conflicting dependency.
I tried a couple of recipes out of internet, including reinstalling all packages, to no avail.
The node version I use is 8.11.0.
I'm not really experienced in using npm or yarn, so perhaps I miss something here.
Here is the output:

npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: arjs-react@0.0.11
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!   peer react@"^17.0.0 || ^18.0.0" from @solana/wallet-adapter-react@0.15.5
npm ERR!   node_modules/@solana/wallet-adapter-react
npm ERR!     @solana/wallet-adapter-react@"^0.15.3" from the root project
npm ERR!     @solana/wallet-adapter-react@"^0.15.3" from @solana/wallet-adapter-react-ui@0.9.7
npm ERR!     node_modules/@solana/wallet-adapter-react-ui
npm ERR!       @solana/wallet-adapter-react-ui@"^0.9.5" from the root project
npm ERR!   4 more (@solana/wallet-adapter-react-ui, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.12.0" from arjs-react@0.0.11
npm ERR! node_modules/arjs-react
npm ERR!   arjs-react@"^0.0.11" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"^16.12.0" from arjs-react@0.0.11
npm ERR!   node_modules/arjs-react
npm ERR!     arjs-react@"^0.0.11" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/yury/.npm/eresolve-report.txt for a full report.

**Comment by nanofuxion** [comment]
Sorry for the **late** response the library is built in the `/dist` folder and you only need install it via:
`yarn add arjs-react` or `npm install arjs-react`

**Comment by nanofuxion** [comment]
please use `yarn add arjs-react` or `npm install arjs-react`
